#! /bin/bash

echo "atualizando o servidor..."
apt-get update
apt-get upgrade -y
apt-get install apache2 -y
apt-get install unzip -y

echo " baixando e copiando os arquivos da aplicação.."

cd /tmp
wget https://github.com/cadhi/linux-site-dio/archive/refs/heads/main.zip
unzip main.zip
cd linux-site-dio-main
cd -R * /var/www/html/
  
